machine.wait_for_unit("multi-user.target")
machine.succeed("echo -n password | cryptsetup luksFormat -q --iter-time=1 /dev/vdb -")
machine.succeed("bootctl set-default nixos-generation-1-specialisation-boot-luks.conf")
machine.succeed("sync")
machine.crash()
machine.start()
machine.wait_for_text("[Pp]assphrase for")
machine.send_chars("password\n")

machine.wait_for_unit("multi-user.target")
machine.succeed("touch /no-persist")
machine.succeed("touch /etc/nixos/persist")
machine.succeed("touch /var/log/persist")
machine.succeed("touch /var/lib/nixos/persist")
machine.succeed("touch /var/lib/systemd/coredump/persist")
machine.succeed("touch /var/lib/tailscale/persist")

machine_id = machine.succeed("cat /etc/machine-id")
ssh_host = machine.succeed("cat /etc/ssh/ssh_host_ed25519_key")

machine.succeed("sync")
machine.crash()
machine.start()
machine.wait_for_text("[Pp]assphrase for")
machine.send_chars("password\n")

machine.wait_for_unit("multi-user.target")
machine.fail("ls /no-persist")
machine.succeed("ls /etc/nixos/persist")
machine.succeed("ls /var/log/persist")
machine.succeed("ls /var/lib/nixos/persist")
machine.succeed("ls /var/lib/systemd/coredump/persist")
machine.succeed("ls /var/lib/tailscale/persist")

assert machine_id in machine.succeed("cat /etc/machine-id")
assert ssh_host in machine.succeed("cat /etc/ssh/ssh_host_ed25519_key")
