name: test-partSingle
on:
  push:
    branches-ignore:
      - main
      - 'ci/**'
  pull_request:
  workflow_dispatch:

jobs:
  partSingle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: configure ssh key
        run: |
          mkdir -p ~/.ssh
          umask 077
          echo "${{ secrets.AVIARY_SECRETS_TEST_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/knownhosts
      - name: run test default
        run: nix run -L .#checks.x86_64-linux.partSingle.driver
