name: test-debug
on:
  push:
    branches: []
  pull_request:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - name: run test debug
        run: nix run -L .#checks.x86_64-linux.debug.driver
