name: update
on:
  workflow_dispatch:
  schedule:
    - cron: '15 1 * * *'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: configure ssh
        run: |
          mkdir -p ~/.ssh
          umask 077
          echo "${{ secrets.AVIARY_SECRETS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/knownhosts
      - name: create branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          PR=$(gh pr list --json number --search "in:title \"[CI] Flake Update\"" | jq -r '.[0].number')
          if (( $PR > 0 )); then
              if [[ "$(gh pr view "$PR" --json mergeStateStatus | jq -r '.mergeStateStatus')" == "CLEAN" ]]; then
                  gh pr merge --auto "$PR" --rebase
                  git pull origin main
              fi
          fi
          git push origin --delete ci/update-flake || true
          git checkout -b ci/update-flake
        env:
          GH_TOKEN: ${{ secrets.AVIARY_FLAKE_UPDATE_PAT }}
      - name: update flake lock 
        run: |
          nix flake update \
            danksearch \
            disko \
            dms \
            dms-plugin-registry \
            dgop \
            firefox-gnome-theme \
            flake-parts \
            hardware \
            home-manager \
            impermanence \
            lanzaboote \
            nixpkgs \
            nixvim \
            nix-minecraft \
            secrets \
            sops-nix
      - name: commit changes
        run: |
          git add .
          git commit -m "ci: update flake lock"
          git push -u origin ci/update-flake
      - name: Create Pull Request
        run: |
          gh pr create --title "[CI] Flake Update" --body "Update flake lock" --base main
        env:
          GH_TOKEN: ${{ secrets.AVIARY_FLAKE_UPDATE_PAT }}
